spring:
  application:
    name: msvc-cursos
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/curso_db
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

server:
  port: 8001

logging:
  level:
    org.hibernate.sql: debug
