spring:
  application:
    name: msvc-usuarios
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios_db
    password: postgres
    username: postgres
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

server:
  port: 8002

logging:
  level:
    org.hibernate.sql: debug
